### ISSUE TITLE
Let, const, promises, async, await, and arrow syntax

### ISSUE THREAD

**Issue by OrangeDrangon** [NectarJS/nectarjs#29] opened 2018-07-12 03:11 UTC
Planned not planned what is the plan on following emcascript

**Comment by adrien-thierry** [comment] 2018-07-12 06:04
It's planned,

NectarJS will follow as much as possible EcmaScript

**Comment by lezsakdomi** [comment] 2018-10-02 21:28
In short it's a duplicate of #4

**Comment by Saiv46** [comment] 2019-06-11 05:01
It's using babel or anything to transpile ES6+ code for now?

**Closed** 2020-02-07 19:42 UTC
Labels: es6, roadmap
